# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SmartCart' do
pod 'MMDrawerController', '~> 0.5.7'
end

target 'SmartCartTests' do

end

target 'SmartCartUITests' do

end

